# -*- coding: utf-8 -*-
"""Atv_CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMct847EpMzwA2GEoYCkBgc_HgC57Vga

# Exercícios – Arquivos CSV
"""

import csv

dados = [
    ['nome', 'nota', 'turma'],
    ['ana', 8.5, '1E'],
    ['beto', 7, '1E'],
    ['Carla', 9.2, '1E'],
]

with open ('turma.csv', 'w', encoding='utf-8', newline= '') as arquivo:
  escrever = csv.writer(arquivo)

  for linha in dados:
      escrever.writerow(linha)

"""Exercício 5 – Criando um CSV
Escreva um programa que peça ao usuário os dados de 3 alunos (nome e duas notas) e
salve tudo em um arquivo chamado turma.csv. A primeira linha deve ser o cabeçalho:
nome,nota1,nota2.
"""

import csv

dados = [
    ['nome', 'nota1', 'nota2'],
    ['ana', 8.5, 8],
    ['beto', 7, 5],
    ['Carla', 9.2, 7],
]

with open ('notas.csv', 'w', encoding='utf-8', newline= '') as arquivo:
  escrever = csv.writer(arquivo)

  for linha in dados:
      escrever.writerow(linha)

"""Exercício 6 – Leitor de notas
Crie manualmente (no bloco de notas) um arquivo chamado notas.csv com o seguinte
conteúdo:
nome,nota1,nota2,nota3
Ana,7.5,8.0,9.0
Beto,5.0,6.0,4.5
Carla,9.0,9.5,10.0
Diego,6.0,7.0,5.5
Escreva um programa que:
a) Leia o arquivo usando csv.DictReader.
b) Calcule a média das três notas de cada aluno.
c) Imprima: &quot;Ana – Média: 8.17 – Aprovada&quot; (aprovado se média &gt;= 6).
"""

import csv

dados = [
    ['nome', 'nota1', 'nota2', 'nota3'],
    ['Ana', 7.5, 8.0, 9.0],
    ['Beto', 5.0, 6.0, 4.5],
    ['Carla', 9.0, 9.5, 10.0],
    ['Diego', 6.0, 7.0, 5.5]
]

with open ('notas1.csv', 'w', encoding='utf-8', newline= '') as arquivo:
  escrever = csv.writer(arquivo)

  for linha in dados:
      escrever.writerow(linha)

with open('notas1.csv', 'r', encoding='utf-8') as arquivo:
    leitor = csv.DictReader(arquivo)
    for linha in leitor:
      nome = linha['nome']
      n1 = float(linha['nota1'])
      n2 = float(linha['nota2'])
      n3 = float(linha['nota3'])
      media = (n1 + n2 + n3) / 3

      if media >= 6:
        status = "Aprovada"

      else:
        status = "Reprovada"

      print(f"{nome} – Média: {media:.2f} – {status}")

"""Exercício 7 – Adicionando uma coluna
Usando o arquivo notas.csv do exercício anterior, escreva um programa que leia os
dados, calcule a média de cada aluno e salve um novo arquivo chamado
notas_com_media.csv contendo as colunas originais mais uma coluna &quot;media&quot;.
"""

dados = [['nome', 'nota1', 'nota2', 'nota3', 'media']]

with open('notas1.csv', 'r', encoding='utf-8') as arquivo:
    leitor = csv.DictReader(arquivo)
    for linha in leitor:
      nome = linha['nome']
      n1 = float(linha['nota1'])
      n2 = float(linha['nota2'])
      n3 = float(linha['nota3'])
      media = (n1 + n2 + n3) / 3

      dados.append([nome, n1, n2, n3, media])

with open('notas_com_media.csv', 'w', encoding='utf-8') as arquivo:
      escrever = csv.writer(arquivo)
      for linha in dados:
        escrever.writerow(linha)

"""Exercício 8 – Filtrando dados
Leia o arquivo notas.csv e crie dois novos arquivos:
aprovados.csv – contendo apenas os alunos com média &gt;= 6.
reprovados.csv – contendo apenas os alunos com média &lt; 6.
Ambos os arquivos devem ter o cabeçalho: nome,media,situacao.
"""

import csv

aprovados = [['nome', 'media', 'situacao']]
reprovados = [['nome', 'media', 'situacao']]

with open('notas1.csv', 'r', encoding='utf-8') as arquivo:
    leitor = csv.DictReader(arquivo)
    for linha in leitor:
      nome = linha['nome']
      n1 = float(linha['nota1'])
      n2 = float(linha['nota2'])
      n3 = float(linha['nota3'])
      media = (n1 + n2 + n3) / 3

      if media >= 6:
        status = "Aprovado"
        aprovados.append([nome, media, status])
      else:
        status = "Reprovado"
        reprovados.append([nome, media, status])

with open('aprovados.csv', 'w', encoding='utf-8') as arquivo:
  escrever = csv.writer(arquivo)
  for linha in aprovados:
    escrever.writerow(linha)

with open('reprovados.csv', 'w', encoding='utf-8') as arquivo:
          escrever = csv.writer(arquivo)
          for linha in reprovados:
            escrever.writerow(linha)