# -*- coding: utf-8 -*-
"""ATV_Arquuivos_de_texto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vAyN8J-nF1_67oD0ZBECLozhTpaHyRll

# Exercícios – Arquivos de Texto
"""

with open('teste.txt', 'w', encoding='utf-8') as arquivo:
  arquivo.write('Primeira linha\n')
  arquivo.write('Segunda linha\n')
  # Adicionar ao final (append)
with open('teste.txt', 'a', encoding= 'utf-8') as arquivo:
  arquivo.write('Terceira linha\n')
# Lendo arquivo com r
with open('teste.txt', 'r', encoding= 'utf-8') as arquivo:
  #Lê o arquivo inteiro como string
  #conteudo = arquivo.read()
  #print(conteudo)
  #for linha in arquivo:
    #print(linha.strip())
  linhas = arquivo.readlines()
  print(linhas)

"""Exercício 1 – Escrevendo um arquivo
Escreva um programa que crie um arquivo chamado frutas.txt contendo o nome de 5
frutas, uma por linha. Depois, abra o arquivo em modo leitura e imprima o conteúdo na
tela.
"""

with open('frutas.txt', 'w', encoding='utf-8') as arquivo:
  arquivo.write('maça\n')
  arquivo.write('uva\n')
  arquivo.write('banana\n')
  arquivo.write('pera\n')
  arquivo.write('abacate\n')

with open('frutas.txt', 'r', encoding= 'utf-8') as arquivo:
  #Lê o arquivo inteiro como string
  conteudo = arquivo.read()
  print(conteudo)

"""Exercício 2 – Lista de compras
Escreva um programa que funcione como uma lista de compras:
a) Peça ao usuário para digitar itens (um por vez).
b) Quando o usuário digitar &#39;sair&#39;, pare de pedir.
c) Salve todos os itens no arquivo compras.txt, um por linha.
d) No final, leia o arquivo e imprima a lista completa.
"""

with open('compras.txt', 'w', encoding= 'utf-8') as arquivo:

  while True:
    lista = input("digite os itens da sua compra:")
    if lista == "sair" or lista == "Sair" :
      break
    lista = lista + "\n"
    arquivo.write(lista)
    print(lista, "Adicionado com sucesso")
  print("Arquivo Salvo")

with open('compras.txt', 'r', encoding= 'utf-8') as arquivo:
  #Lê o arquivo inteiro como string
  conteudo = arquivo.read()
  print(conteudo)

"""Exercício 3 – Diário de bordo
Escreva um programa que peça ao usuário para digitar uma anotação. O programa deve
salvar a anotação no arquivo diario.txt, adicionando a data e hora atuais antes do texto.
Use o modo append para que cada execução adicione ao final sem apagar as anteriores.
Dica: para pegar a data e hora atual:
"""

from datetime import datetime
agora = datetime.now().strftime(';%d/%m/%Y %H:%M')

with open('diario.txt', 'w', encoding= 'utf-8') as arquivo:
    arquivo.write(agora + "\n")

with open('diario.txt', 'a', encoding= 'utf-8') as arquivo:
    while True:
      anota = input("digite sua anotação:")
      if anota == 'sair' or anota == "Sair":
        break
      anota += "\n"
      arquivo.write(anota)

with open('diario.txt', 'r', encoding= 'utf-8') as arquivo:
  #Lê o arquivo inteiro como string
  conteudo = arquivo.read()
  print(conteudo)

"""Exercício 4 – Contador de linhas e palavras
Escreva um programa que leia um arquivo de texto qualquer (pode ser o diario.txt) e
imprima:
a) Quantas linhas o arquivo tem.
b) Quantas palavras o arquivo tem no total.
Dica: leia linha por linha e use split() para contar palavras em cada linha.
"""

with open('diario.txt', 'r', encoding= 'utf-8') as arquivo:
 linhas = arquivo.readlines()
 print(len(linhas))

with open('diario.txt', 'r', encoding='utf-8') as arquivo:
    for i, linha in enumerate(arquivo, 1):
        # .split() sem argumentos remove espaços extras e divide palavras
        palavras = linha.split()
        num_palavras = len(palavras)
        print(f"Linha {i}: {num_palavras} palavras")