# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDKkUA_y9wcGF2hhgI__vTGYUCErXys2

# Exercícios – Listas

Exercício 1 – Criando e manipulando uma lista
Crie uma lista chamada notas com as notas: 7.5, 8.0, 6.0, 9.5, 5.0.
Em seguida:
  a) Adicione a nota 8.5 ao final da lista.
"""

notas = [7.5, 8.0, 6.0, 9.5, 5.0]
notas.append(8.5)

print(notas)

""" b) Substitua a nota 5.0 pelo valor 6.5.

"""

notas = [7.5, 8.0, 6.0, 9.5, 5.0]
notas.remove(5.0)
notas.append(6.5)

print(notas)

"""c) Imprima a lista ordenada do maior para o menor (dica: sort tem um parâmetro reverse).

"""

notas = [7.5, 8.0, 6.0, 9.5, 5.0]
notas.sort(reverse=True)

print(notas)

""" d) Imprima a maior nota e a menor nota usando as funções max() e min().

"""

notas = [7.5, 8.0, 6.0, 9.5, 5.0]
maior = max(notas)
menor = min(notas)

print(maior)
print(menor)

"""Exercício 2 – Iterando com enumerate
Crie uma lista com os nomes de 5 colegas de turma.
Use um laço for com enumerate para imprimir cada nome no formato:
  "Aluno 1: João"
  "Aluno 2: Maria"  ... e assim por diante.


"""

colegas = ['Lucas', 'Arthur', 'Ana', 'Marcos', 'Bernardo']

for i, colegas in enumerate(colegas) :

  print(f'{i+1}: {colegas}')

"""Exercício 3 – Filtrando elementos
Dada a lista: numeros = [3, 17, 8, 42, 5, 100, 23, 66, 11, 99]
Escreva um programa que:
  a) Imprima apenas os números pares.


"""

numeros = [3, 17, 8, 42, 5, 100, 23, 66, 11, 99]

for numero in numeros :
  if numero%2 == 0 :
    print(numero)

"""  b) Crie uma nova lista somente com os números maiores que 20.


"""

numeros = [3, 17, 8, 42, 5, 100, 23, 66, 11, 99]

nova_lista = []

for numero in numeros :
  if numero > 20 :

    nova_lista.append(numero)
print(nova_lista)

""" c) Imprima a soma de todos os números da lista original usando sum().

"""

numeros = [3, 17, 8, 42, 5, 100, 23, 66, 11, 99]
total = sum(numeros)
print(total)

"""Exercício 4 – Fatiamento
Crie uma lista com os números de 1 a 10 (pode usar range).
Use fatiamento para:
  a) Imprimir os primeiros 4 elementos.


"""

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(numeros[:4])

"""  b) Imprimir os últimos 3 elementos."""

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(numeros[7:])

"""c) Imprimir apenas os elementos nas posições pares (0, 2, 4, ...)."""

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(numeros[1::2])

"""Exercício 5 – Listas aninhadas (lista dentro de lista)
Crie uma lista chamada turma em que cada elemento é uma lista com
[nome, nota]. Exemplo: turma = [['Ana', 8.5], ['Beto', 7.0], ...]
Coloque pelo menos 4 alunos.
Depois, percorra a lista e imprima:
  "Ana tirou 8.5"
  "Beto tirou 7.0"  ... para cada aluno.


"""

turma = [['Lucas',9.0], ['Marcos', 6.0], ['Raí',5.5], ['Arthur',2.0]]

for i, alunos in enumerate(turma) :
  print(f'{turma[i][0]} tirou {turma[i][1]}')

"""Exercício 6 – Desafio – Remoção condicional
Escreva uma função limpar_reprovados(lista_notas) que receba
uma lista de notas e retorne uma nova lista contendo apenas
as notas maiores ou iguais a 6.0.
Teste com: [5.0, 7.0, 4.5, 9.0, 6.0, 3.0, 8.5]
Resultado esperado: [7.0, 9.0, 6.0, 8.5]


"""

def  limpar_reprovados(lista_notas):
  notas_aprovadas = []
  for nota in lista_notas:
    if nota >=6.0 :
      notas_aprovadas.append(nota)

  return notas_aprovadas
lista_notas = [5.0, 7.0, 4.5, 9.0, 6.0, 3.0, 8.5]
resultado = limpar_reprovados(lista_notas)
print(resultado)