# -*- coding: utf-8 -*-
"""ATV_DICT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_T0v8tVV--AtuQSZnrago1X9YdrAAgD

# Exercícios – Dicionários

Exercício 11 – Cadastro simples
Crie um dicionário chamado contato com as chaves:
  nome, telefone, email e cidade.
Preencha com dados fictícios.
Depois:
  a) Imprima todas as chaves e valores usando .items().
"""

contato = {
    'nome': 'Roger',
    'telefone': 4002-8922,
    'email': 'lucasgmf089@gmail.com',
    'cidade': 'RP',
}
for chave, valor in contato.items():
    print(f'{chave}: {valor}')

"""b) Adicione uma chave 'instagram' com um valor qualquer.

"""

contato = {
    'nome': 'Roger',
    'telefone': 4002-8922,
    'email': 'lucasgmf089@gmail.com',
    'cidade': 'RP',
}
contato['instagram'] = 'lucas_gmf08'
for chave, valor in contato.items():
    print(f'{chave}: {valor}')

"""  c) Remova a chave 'telefone'."""

contato = {
    'nome': 'Roger',
    'telefone': 4002-8922,
    'email': 'lucasgmf089@gmail.com',
    'cidade': 'RP',
}
del contato['telefone']
for chave, valor in contato.items():
    print(f'{chave}: {valor}')

"""d) Verifique (com if/in) se a chave 'email' existe e imprima uma mensagem.

"""

contato = {
    'nome': 'Roger',
    'telefone': 4002-8922,
    'email': 'lucasgmf089@gmail.com',
    'cidade': 'RP',
}

if 'email' in contato:
    print('Chave existe!')

else :
  print('Chave não existe')

for chave, valor in contato.items():
    print(f'{chave}: {valor}')

"""Exercício 12 – Contando ocorrências
Dada a string frase = 'o rato roeu a roupa do rei de roma'
escreva um programa que conte quantas vezes cada palavra aparece.
Use um dicionário onde a chave é a palavra e o valor é a contagem.
Dica: use frase.split() para obter a lista de palavras.
Saída esperada (pode variar a ordem):
  {'o': 2, 'rato': 1, 'roeu': 1, 'a': 1, 'roupa': 1, 'do': 1, 'rei': 1, 'de': 1, 'roma': 1}


"""

frase = 'a rata roeu a roupa do rei de roma'

palavras = frase.split()

contagem = {}

for palavra in palavras:
    if palavra in contagem:
        contagem[palavra] += 1
    else:
        contagem[palavra] = 1

print(contagem)

"""Exercício 13 – Dicionário de alunos
Crie um dicionário turma onde cada chave é o nome de um aluno
e o valor é uma lista de 3 notas. Inclua pelo menos 4 alunos.
Escreva um programa que percorra o dicionário e imprima:
  "Ana – Média: 8.2 – Situação: Aprovado"
A situação é Aprovado se a média >= 6.0, caso contrário Reprovado.


"""

turma = {
    'Lucas' : [1, 2, 3],
    'Arthur' : [4, 5, 6],
    'Ana' : [9, 3, 7],
    'Marcos' : [8, 10, 5],
}

for alunos, notas in turma.items():
  média = sum(notas) / len(notas)
  if média >= 6.0 :
    print(f'Os alunos {alunos} foram Aprovados, com média {média}')
  else :
     print(f'Os alunos {alunos} foram Reprovados, com média {média}')

"""Exercício 14 – Mesclando (Juntando) dicionários
Você tem dois dicionários com informações de um produto:
  info1 = {'nome': 'Notebook', 'preco': 3500.00}
  info2 = {'marca': 'TechBrand', 'estoque': 15}
Crie um terceiro dicionário produto que contenha todos os
pares de info1 e info2 juntos.
Depois altere o preço para 3200.00 e imprima o dicionário final.
Dica: pesquise o operador ** para mesclar dicionários ou use .update().


"""

info1 = {'nome': 'Notebook', 'preco': 3500.00}

info2 = {'marca': 'TechBrand', 'estoque': 15}

info1['preco'] = 3200.00

marged = info1 | info2

print(marged)

"""Exercício 15 – Desafio – Agenda telefônica
Implemente uma agenda telefônica simples com as operações:
  adicionar_contato(agenda, nome, telefone)
  buscar_contato(agenda, nome)  → imprime o telefone ou 'Não encontrado'
  remover_contato(agenda, nome)
  listar_contatos(agenda)       → imprime todos em ordem alfabética


Teste criando uma agenda com 4 contatos e chamando cada função.
Dica: para ordenar as chaves de um dicionário, use sorted(agenda.keys()).


"""

# O CHAT QUE FEZ, NÃO ME RESPONSABILIZO

def adicionar_contato(agenda, nome, telefone):
    agenda[nome] = telefone
    print(f"Contato {nome} adicionado com sucesso.")

def buscar_contato(agenda, nome):
    if nome in agenda:
        print(f"Telefone de {nome}: {agenda[nome]}")
    else:
        print(f"Contato {nome} não encontrado.")

def remover_contato(agenda, nome):
    if nome in agenda:
        del agenda[nome]
        print(f"Contato {nome} removido com sucesso.")
    else:
        print(f"Contato {nome} não encontrado para remoção.")

def listar_contatos(agenda):
    if not agenda:
        print("Agenda vazia.")
        return
    print("--- Contatos na Agenda ---")
    for nome in sorted(agenda.keys()):
        print(f"{nome}: {agenda[nome]}")
    print("--------------------------")

# Teste da agenda telefônica
agenda = {}

print("\n--- Adicionando contatos ---")
adicionar_contato(agenda, "Alice", "1111-1111")
adicionar_contato(agenda, "Bob", "2222-2222")
adicionar_contato(agenda, "Carlos", "3333-3333")
adicionar_contato(agenda, "Diana", "4444-4444")
adicionar_contato(agenda, "Ana", "5555-5555") # Adicionando mais um para testar ordenação

print("\n--- Listando contatos ---")
listar_contatos(agenda)

print("\n--- Buscando contatos ---")
buscar_contato(agenda, "Bob")
buscar_contato(agenda, "Eva")

print("\n--- Removendo contatos ---")
remover_contato(agenda, "Carlos")
remover_contato(agenda, "Eva")

print("\n--- Listando contatos após remoção ---")
listar_contatos(agenda)

print("\n--- Buscando contato removido ---")
buscar_contato(agenda, "Carlos")