# -*- coding: utf-8 -*-
"""TRABALHO_LUCAS_THAMIRYS_LAÍZA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGr-K9T04VQ_pkR2L8uEBBbzmHZfYTDF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/video_games_sales.csv')

# PARTE 1 - CARREGAMENTO E EXPLORAÇÃO INICIAL
print("\n AS 5 PRIMEIRAS LINHAS")
display(df.head())

print("\n QUANTIDADE DE LINHAS E COLUNAS ")
print("Existem", df.shape[0], "linhas e", df.shape[1], "colunas")

print("\n TIPOS DE DADOS ")
print(df.dtypes)

print("\n RESUMO GERAL ")
df.info()
'''Aqui verificamos se o Pandas interpretou os dados corretamente.
Por exemplo, se uma coluna de 'Data' ou 'Preço' foi lida como texto (object), precisaremos convertê-la para o formato numérico ou temporal antes da análise.
Além disso, o info() nos mostra se existem valores nulos (dados faltantes), o que exigiria uma limpeza prévia'''

print("\n ESTATÍSTICAS DESCRITIVAS ")
display(df.describe())

# PARTE 2 — LIMPEZA DOS DADOS
print("\n ===== ANTES DA LIMPEZA =====")
print("Shape:", df.shape)
df.info()

# 1. VALORES AUSENTES
print("\n VALORES NULOS POR COLUNA:")
print(df.isnull().sum())

# Estratégia:
# - Colunas numéricas: preencher com a mediana (evita distorção por valores extremos)
# - Colunas categóricas: preencher com "Desconhecido"
# Justificativa: mantém o máximo de dados possível sem perder linhas

for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        df[col].fillna(df[col].median(), inplace=True)
    else:
        df[col].fillna('Desconhecido', inplace=True)

# 2. TIPOS DE DADOS
print("\n TIPOS DE DADOS (ANTES):")
print(df.dtypes)

# Exemplo: garantir que colunas numéricas estejam corretas
# (ajuste conforme seu dataset)
colunas_numericas = df.select_dtypes(include=['float64', 'int64']).columns

for col in colunas_numericas:
    df[col] = df[col].astype(float)

print("\n TIPOS DE DADOS (DEPOIS):")
print(df.dtypes)

# 3. REMOÇÃO DE COLUNAS DESNECESSÁRIAS
# Exemplo: remover colunas irrelevantes como ID ou URL (se existirem)
colunas_remover = [col for col in df.columns if 'id' in col.lower() or 'url' in col.lower()]

df.drop(columns=colunas_remover, inplace=True, errors='ignore')

print("\n Colunas removidas:", colunas_remover)

# 4. DUPLICATAS
duplicados = df.duplicated().sum()
print("\n Registros duplicados:", duplicados)

# Removendo duplicatas
df.drop_duplicates(inplace=True)

# RESULTADO FINAL
print("\n ===== DEPOIS DA LIMPEZA =====")
print("Shape:", df.shape)
df.info()

# Parte 3 — Análise e Manipulação com Pandas e NumPy
# Filtros
filtro1 = df[(df['global_sales'] > 10) & (df['year'] > 2010)]
print("\nFiltro 1:", filtro1.shape[0])
display(filtro1.head())

filtro2 = df[(df['genre'] == 'Action') | (df['genre'] == 'Sports')]
print("\nFiltro 2:", filtro2.shape[0])
display(filtro2.head())

filtro3 = df[~(df['platform'] == 'PS4')]
print("\nFiltro 3:", filtro3.shape[0])
display(filtro3.head())

# Ordenação
print("\nTOP 10:")
display(df.sort_values(by='global_sales', ascending=False).head(10))

print("\nBOTTOM 10:")
display(df.sort_values(by='global_sales').head(10))

# Agrupamento
agrupado = df.groupby('genre')['global_sales'].agg(['mean','sum','count'])
display(agrupado)

# NumPy
print("\nDesvio padrão:", np.std(df['global_sales']))
print("Variância:", np.var(df['global_sales']))

# Normalização
df['global_sales_normalizado'] = (
    (df['global_sales'] - np.min(df['global_sales'])) /
    (np.max(df['global_sales']) - np.min(df['global_sales']))
)

print("\nColuna normalizada criada:")
display(df[['global_sales', 'global_sales_normalizado']].head())

# PARTE 4 — GRÁFICOS

# 1. Barras
plt.figure(figsize=(10,6))
df.groupby('genre')['global_sales'].sum().sort_values().plot(kind='bar', color='skyblue')
plt.title("Vendas por Gênero")
plt.xlabel("Gênero")
plt.ylabel("Vendas")
plt.savefig("barras.png")
plt.show()

# 2. Gráfico de vendas por ano
plt.figure(figsize=(10,6))
df.groupby('year')['global_sales'].sum().plot(kind='bar', color='salmon')
plt.title("Vendas Globais por Ano")
plt.xlabel("Ano")
plt.ylabel("Vendas")
plt.savefig("vendas_por_ano.png")
plt.show()

# 3. Scatter
plt.figure(figsize=(8,6))
plt.scatter(df['NA_sales'], df['global_sales'], color='purple', alpha=0.5)
plt.title("NA vs Global")
plt.xlabel("NA Sales")
plt.ylabel("Global Sales")
plt.savefig("scatter.png")
plt.show()

# 4. Linha
plt.figure(figsize=(10,6))
df.groupby('year')['global_sales'].sum().plot(color='green', marker='o')
plt.title("Vendas ao longo dos anos")
plt.xlabel("Ano")
plt.ylabel("Vendas")
plt.savefig("linha.png")
plt.show()

# BÔNUS

# Heatmap
plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Mapa de Correlação")
plt.savefig("heatmap.png")
plt.show()

# Subplots
fig, axes = plt.subplots(1,2, figsize=(14,5))

axes[0].bar(
    df.groupby('year')['global_sales'].sum().index,
    df.groupby('year')['global_sales'].sum().values,
    color='orange'
)
axes[0].set_title("Vendas por Ano")
axes[0].set_xlabel("Ano")
axes[0].set_ylabel("Vendas")

axes[1].scatter(df['NA_sales'], df['global_sales'], color='green')
axes[1].set_title("Mapa de Dispersão")

plt.savefig("subplots.png")
plt.show()

# Interativo — vendas por região ao longo dos anos
coluna = input(
    "Digite uma coluna de vendas "
    "(NA_sales, EU_sales, Japan_sales, other_sales, global_sales): "
)

plt.figure(figsize=(10,6))
df.groupby('year')[coluna].sum().plot(marker='o')

plt.title(f"Vendas por Ano - {coluna}")
plt.xlabel("Ano")
plt.ylabel("Vendas")
plt.savefig("interativo.png")
plt.show()